language: cpp
sudo: required

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: GCC_VERSION=4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.9
          - libgmp-dev
          - libgmpxx4ldbl

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: GCC_VERSION=5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
          - libgmp-dev
          - libgmpxx4ldbl

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: GCC_VERSION=6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - libgmp-dev
          - libgmpxx4ldbl

    # - os: linux
    #   sudo: required
    #   dist: trusty
    #   compiler: clang
    #   env: COMPILER=clang++
    #   addons:
    #     apt:
    #       sources:
    #       - ubuntu-toolchain-r-test
    #       packages:
    #       - libgmp-dev
    #       - libgmpxx4ldbl
    #   before_install:
    #   - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
    #   - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    #   - sudo apt-get update -qq 
    #   - sudo apt-get install -qq -y clang-format-3.9

    - os: osx
      compiler: clang
      before_install:
      - brew update
      - brew uninstall automake && brew install automake
      - brew install autoconf libtool

install:
  - export CC=${CC}${GCC_VERSION:+-${GCC_VERSION}}
  - echo "CC=${CC}"
  - export CXX=${CXX}${GCC_VERSION:+-${GCC_VERSION}}
  - echo "CXX=${CXX}"

before_script:
  - ./autogen.sh

script:
  - make
  - make check
  - make benchmarks
  - make examples
  - make dist

after_failure:
  - cat config.log

notifications:
  on_success: change
  on_failure: always
